matrix:
  fast_finish: true
  include:
    # QT5 based build with Python 3 // using container based builds and prebuild binary dependencies in osgeo4travis
    - os: linux
      services: docker
      language: python # This lets us use newer python versions from virtualenv
      env:
        - TRAVIS_CONFIG=linux
        - DOCKER_COMPOSE=${TRAVIS_BUILD_DIR}/.docker/docker-compose.travis.yml
        - DOCKER_TAG=$( [[ $TRAVIS_REPO_SLUG =~ qgis/QGIS ]] && echo $TRAVIS_BRANCH | sed 's/master/latest/' || echo "latest" )
        - DOCKER_DEPS_PUSH=$( [[ $TRAVIS_REPO_SLUG =~ qgis/QGIS ]] && [[ $TRAVIS_EVENT_TYPE =~ push ]] && echo "true" || echo "false" )
        - DOCKER_DEPS_IMAGE_REBUILD=$( [[ $TRAVIS_COMMIT_MESSAGE =~ '[docker] update dependencies' ]] && echo "true" || echo "false" )
        # on cron job, QGIS image is built and push without testing
        - DOCKER_QGIS_IMAGE_BUILD_PUSH=$( [[ $TRAVIS_REPO_SLUG =~ qgis/QGIS ]] && [[ $TRAVIS_EVENT_TYPE =~ cron ]] && echo "true" || echo "false" )
        - QGIS_LAST_BUILD_SUCCESS=true # TODO use API to know if last build succeed https://developer.travis-ci.com/resource/builds
        - CCACHE_DIR=${HOME}/.ccache
      dist: trusty
      sudo: false
      cache:
        apt: true
        pip: true
        directories:
          - $HOME/.ccache
        timeout: 1000
      compiler: clang
      python: "3.5"
      addons:
        apt:
          sources:
          packages:


    - os: linux
      language: python
      python: "3.5"
      env:
        - TRAVIS_CONFIG=code_layout
      dist: trusty
      sudo: false
      cache:
        apt: true
      addons:
        apt:
          sources:
            - sourceline: 'ppa:jonathonf/backports'  # silversearcher-ag backport
            - sourceline: 'ppa:sergey-dryabzhinsky/packages' # doxygen
          packages:
            - doxygen
            - graphviz
            - txt2tags
            - pkg-config
            - xvfb
            - flip
            # used for spell checks
            - perl  # sipify, lookahead regex in spell check script
            - silversearcher-ag
            - expect-dev  # unbuffer
            - coreutils
            - libyaml-tiny-perl
    # OSX based build with QT4 and Python 2
#    - os: osx
#      osx_image: xcode8.3 # MacOS 10.12: Sierra
#      cache:
#        pip: true
#        directories:
#          - $HOME/.ccache
#      env:
#        - TRAVIS_CONFIG=macos
#        - IGNORE_BUILD_FAILURES=YES
#
#  allow_failures:
#    - os: osx

git:
  depth: 120

notifications:
  irc: "chat.freenode.net#qgis-test"
  on_failure: change
  on_success: change
  skip_join: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/467e3aff72e344d1dae3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never # default: never

before_install:
  - ./.ci/travis/${TRAVIS_CONFIG}/before_install.sh

install:
  - ./.ci/travis/${TRAVIS_CONFIG}/install.sh

before_script:
  - ./.ci/travis/${TRAVIS_CONFIG}/before_script.sh

script:
  - ./.ci/travis/${TRAVIS_CONFIG}/script.sh

after_script:
  - ./.ci/travis/${TRAVIS_CONFIG}/after_script.sh
